### ISSUE TITLE
很赞的项目

### ISSUE THREAD

**Issue by HarryChen0506** [LinWeb/blog#4]
你的这个项目挺小清新的哈。react-markdown-editor-lite最近升级了，可以自定义解析器以及样式也优化了一下

**Comment by LinWeb** [comment]
谢谢，你开源的markdown组件很nice，向你学习，想找个时间自己捣鼓一个类似的markdown组件，以后请多多指教。

**Comment by HarryChen0506** [comment]
多谢支持。找个小方向，做点轮子挺有意思的，一起进步哈

**Comment by LinWeb** [comment]
是的，搞技术就是多折腾没有尝试过的东西
